### ISSUE TITLE
toAxisPosition should return double value?

### ISSUE THREAD

**Issue by dileepbapat** [GwtMaterialDesign/gwt-material-am4charts#11]
https://github.com/GwtMaterialDesign/gwt-material-amcharts4/blob/09caa9879861a91c23fdefdaa4fd5f68940f649d/src/main/java/gwt/material/design/amcharts/client/axis/Axis.java#L141

**Comment by kevzlou7979** [comment]
Can you link the amcharts official documentation regarding this. Thanks

**Comment by dileepbapat** [comment]
https://www.amcharts.com/docs/v4/reference/axis/#toAxisPosition_method

**Comment by kevzlou7979** [comment]
Oh i was thinking if the axis position can be 0.5 as the range itself is from `0 - 1`

**Comment by kevzlou7979** [comment]
Try reading this https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/#Accounting_for_zoom

**Comment by kevzlou7979** [comment]
I tried to test there own demo and it turns out that the axis position is double.
![image](https://user-images.githubusercontent.com/3138071/81752663-7f743d00-94e4-11ea-9357-b0dcad7cfe7e.png)
