### ISSUE TITLE
SnapToSeries Property for Cursor

### ISSUE THREAD

**Issue by mophima** [GwtMaterialDesign/gwt-material-am4charts#18]
Hello, 
I've been wondering whether the Cursor-Property "SnapToSeries" (https://www.amcharts.com/docs/v4/reference/xycursor/#snapToSeries_property) is currently working, or if the implementation is planned for the future. 
Thanks for all your amazing work!

**Comment by kevzlou7979** [comment]
What version does Amcharts4 support SnapToSeries? Can you point me to changelog so that I can patch the latest Amcharts GWT Integration.

**Comment by kevzlou7979** [comment]
Ok will be adding this feature, for later reference https://www.componentsource.com/product/amcharts/releases

**Comment by kevzlou7979** [comment]
Will be patching Amcharts4 2.5.0-SNAPSHOT

**Comment by kevzlou7979** [comment]
Another Reference https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Snapping_to_data_items

**Comment by kevzlou7979** [comment]
Patched via https://github.com/GwtMaterialDesign/gwt-material-amcharts4/pull/19/commits/703ea8b6a03005eac11af455e9684fa73d395dca. You can test now the feature if it's working.

**Comment by mophima** [comment]
Works perfectly now, thank You!

**Comment by kevzlou7979** [comment]
Cool
